// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtCcorf9cOv8H_regHfniPzMCcAobyjN0',
    appId: '1:400707887159:web:9a46dbfe68715d9ccd9fb2',
    messagingSenderId: '400707887159',
    projectId: 'batilink-8b815',
    authDomain: 'batilink-8b815.firebaseapp.com',
    storageBucket: 'batilink-8b815.firebasestorage.app',
    measurementId: 'G-VDYVSP284W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW35JtbLh98q7jk_UeAp6Uo09Ke0IC_lM',
    appId: '1:400707887159:android:9d25235c51169bdbcd9fb2',
    messagingSenderId: '400707887159',
    projectId: 'batilink-8b815',
    storageBucket: 'batilink-8b815.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgHIZe3G45LCYmW3i8aAuN_mW72u6hGCg',
    appId: '1:400707887159:ios:f0c82b8fe59d0319cd9fb2',
    messagingSenderId: '400707887159',
    projectId: 'batilink-8b815',
    storageBucket: 'batilink-8b815.firebasestorage.app',
    iosBundleId: 'com.example.batilinkMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgHIZe3G45LCYmW3i8aAuN_mW72u6hGCg',
    appId: '1:400707887159:ios:f0c82b8fe59d0319cd9fb2',
    messagingSenderId: '400707887159',
    projectId: 'batilink-8b815',
    storageBucket: 'batilink-8b815.firebasestorage.app',
    iosBundleId: 'com.example.batilinkMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtCcorf9cOv8H_regHfniPzMCcAobyjN0',
    appId: '1:400707887159:web:4a083c8b5b2f8119cd9fb2',
    messagingSenderId: '400707887159',
    projectId: 'batilink-8b815',
    authDomain: 'batilink-8b815.firebaseapp.com',
    storageBucket: 'batilink-8b815.firebasestorage.app',
    measurementId: 'G-SK44YT0LP2',
  );
}
